In [3]:
import numpy as np
import pandas as pd


In [4]:
data = open('spambase.data').read().split("\n")
data = [i.split(",") for i in (data)]
column = open('features','r').read().split("\n")
column =[i.strip() for i in column]
dataset =  pd.DataFrame(data, columns=column)
dataset=dataset.convert_objects(convert_numeric=True)
dataset=dataset.dropna()
columnmax = [max(dataset[i]) for i in dataset.columns]
columnmin = [min(dataset[i]) for i in dataset.columns]
for i,j in enumerate(dataset.columns):
    dataset[j] = (dataset[j] - columnmin[i])/columnmax[i]
dataset['class']= dataset['class'].astype(int)
# dataset.insert(0,'Bias',1)
dataset['class'].value_counts()

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:6: FutureWarning: convert_objects is deprecated.  To re-infer data dtypes for object columns, use DataFrame.infer_objects()
For all other conversions use the data-type specific converters pd.to_datetime, pd.to_timedelta and pd.to_numeric.
  


0    2788
1    1813
Name: class, dtype: int64

In [5]:
def mean_squared(W,X,Y):
    return np.sum((np.dot(X,np.transpose(W))-Y)**2)

In [6]:
def training(learning_rate,initial_weights,m,dataset,bias):
    diff = 10000000000
    Y = np.asarray(list(dataset['class']))
    X = dataset.drop(columns=['class']).values
    X=np.insert(X, 0, bias, axis=1)
    XT=np.transpose(X)
    w_old = initial_weights
    d_old = mean_squared(initial_weights,X,Y)
    lm = learning_rate/m
    while diff >0.0000000000001:
        w_new = (w_old - (lm * (np.dot(XT,(np.dot(X,w_old.T))-Y))))
        d_new = mean_squared(w_new,X,Y)
        diff = abs(d_new-d_old)
        d_old=(d_new)
        w_old =(w_new)
    return w_old
    

In [7]:
def testing(row,weights,bias):
    Y=(row['class'])
    X = np.asarray(list(row[:-1]))
    X=np.insert(X,0,bias)
    
    s=0
    for i in range(len(X)):
        s+=(X[i]*weights[i])
    if s>0.37:
        return 1
    else:
        return 0

In [8]:
def accuracy(prediction,test_dataset):
    test=list(test_dataset['class'])
    ac = zip(prediction,test)
    right =0
    for k,v in ac:
        if k ==v:
            right+=1
    return right/len(prediction)

In [9]:
dataset = dataset.sample(frac=1)

b=0
while b<=0.5:
    ac=[]
    for i in range(0,len(dataset),920):
        print(i)
        if i+920<len(dataset):
            bias=0.13   
            training_dataset=pd.concat([dataset[i+920:],dataset[0:i]])
            n = len(training_dataset.columns)-1
            m = len(training_dataset)
            W=np.random.rand(n+1)
            print(W)
            test_dataset=dataset[i:i+920]
            weights=training(0.9,W,m,training_dataset,bias)
            prediction=[]
            for index,row in test_dataset.iterrows():
                prediction.append(testing(row,weights,bias))
            acc = accuracy(prediction,test_dataset)
            print(acc)
            ac.append(acc)
    print(np.sum(np.asarray(ac))/5)
    b+=0.01

0
[0.39299825 0.55174253 0.56168443 0.19327727 0.40465526 0.82273622
 0.60593554 0.57121773 0.33656865 0.65489134 0.73217497 0.34301635
 0.57961998 0.06333794 0.31255584 0.60858662 0.19133326 0.67919943
 0.18512852 0.02748675 0.4250278  0.68598184 0.06342571 0.61019324
 0.5076199  0.96461375 0.5235876  0.02356952 0.44922418 0.81473418
 0.45877409 0.23025861 0.08328027 0.79113764 0.99634023 0.0358845
 0.1766804  0.26002473 0.09195485 0.28009451 0.40534903 0.34275486
 0.47168701 0.11012816 0.34209395 0.03057115 0.27942145 0.65264778
 0.04084037 0.58805968 0.1926489  0.96885098 0.23811038 0.2326728
 0.78985254 0.49753629 0.72942491 0.17630391]
0.9
920
[0.37059793 0.41185311 0.06103179 0.49219974 0.71031292 0.59547945
 0.57415927 0.18555549 0.68602442 0.24854752 0.71846804 0.85859282
 0.51893769 0.85513412 0.22124309 0.83490906 0.04613238 0.83229833
 0.48377504 0.43348703 0.33045174 0.4919946  0.09601654 0.85965718
 0.10609379 0.66712466 0.17269047 0.02583054 0.03936076 0.01696185
 0.08649

KeyboardInterrupt: 

In [16]:
ac

[]

array([0.62263766, 0.9335026 , 0.29797037, ..., 0.15312717, 0.61044247,
       0.72430497])

In [102]:
a=np.asarray([1,2,3])
b = np.asarray([[4,5,6]])

In [103]:
np.matmul(b,np.transpose(a))

array([32])

In [104]:
b-a

array([[3, 3, 3]])