In [3]:
import numpy as np
import pandas as pd


In [4]:
data = open('spambase.data').read().split("\n")
data = [i.split(",") for i in (data)]
column = open('features','r').read().split("\n")
column =[i.strip() for i in column]
dataset =  pd.DataFrame(data, columns=column)
dataset=dataset.convert_objects(convert_numeric=True)
dataset=dataset.dropna()
columnmax = [max(dataset[i]) for i in dataset.columns]
columnmin = [min(dataset[i]) for i in dataset.columns]
for i,j in enumerate(dataset.columns):
    dataset[j] = (dataset[j] - columnmin[i])/columnmax[i]
dataset['class']= dataset['class'].astype(int)
# dataset.insert(0,'Bias',1)
dataset['class'].value_counts()

/Users/shaivalpatel/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:6: FutureWarning: convert_objects is deprecated.  To re-infer data dtypes for object columns, use DataFrame.infer_objects()
For all other conversions use the data-type specific converters pd.to_datetime, pd.to_timedelta and pd.to_numeric.
  


0    2788
1    1813
Name: class, dtype: int64

In [5]:
def mean_squared(W,X,Y):
    return np.sum((np.dot(X,np.transpose(W))-Y)**2)

In [8]:
def training(learning_rate,initial_weights,m,dataset,bias):
    diff = 10000000000
    Y = np.asarray(list(dataset['class']))
    X = dataset.drop(columns=['class']).values
    X=np.insert(X, 0, bias, axis=1)
    XT=np.transpose(X)
    w_old = initial_weights
    d_old = mean_squared(initial_weights,X,Y)
    lm = learning_rate/m
    while diff >0.0000000000001:
        w_new = (w_old - (lm * (np.dot(XT,(np.dot(X,w_old.T))-Y))))
        d_new = mean_squared(w_new,X,Y)
        diff = abs(d_new-d_old)
        d_old=(d_new)
        w_old =(w_new)
    return w_old
    

In [9]:
def testing(row,weights,bias):
    Y=(row['class'])
    X = np.asarray(list(row[:-1]))
    X=np.insert(X,0,bias)
    
    s=0
    for i in range(len(X)):
        s+=(X[i]*weights[i])
    if w_sum>0.37:
        return 1
    else:
        return 0

In [14]:
def accuracy(prediction,test_dataset):
    test=list(test_dataset['class'])
    ac = zip(prediction,test)
    right =0
    for k,v in ac:
        if k ==v:
            right+=1
    return right/len(prediction)

In [15]:
dataset = dataset.sample(frac=1)

b=0
while b<=0.5:
    ac=[]
    for i in range(0,len(dataset),920):
        print(i)
        if i+920<len(dataset):
            bias=0.13   
            training_dataset=pd.concat([dataset[i+920:],dataset[0:i]])
            n = len(training_dataset.columns)-1
            m = len(training_dataset)
            W=np.random.rand(n+1)
            print(W)
            test_dataset=dataset[i:i+920]
            weights=training(0.9,W,m,training_dataset,bias)
            prediction=[]
            for index,row in test_dataset.iterrows():
                prediction.append(testing(row,weights,bias))
            acc = accuracy(prediction,test_dataset)
            print(acc)
            ac.append(acc)
    print(np.sum(np.asarray(ac))/5)
    b+=0.01

0
[0.64487497 0.17522986 0.33995882 0.01954566 0.88143324 0.91746452
 0.18183615 0.5365826  0.42393731 0.47509667 0.45060533 0.06942445
 0.4961199  0.74840716 0.18065963 0.25241034 0.21817531 0.10929768
 0.2426998  0.06298901 0.80622202 0.78543045 0.62693186 0.20390462
 0.35049976 0.88327499 0.73833622 0.51709212 0.52659729 0.36940172
 0.97700677 0.23117874 0.12534932 0.99950444 0.07452296 0.28486724
 0.46475322 0.1586191  0.4535429  0.85847382 0.91017541 0.1383842
 0.3779353  0.77292164 0.22002801 0.51986649 0.87019121 0.97243127
 0.2394242  0.35206761 0.04691031 0.50194238 0.06490679 0.53358123
 0.44635825 0.64041998 0.09852083 0.90161234]
920
[0.46013107 0.60036648 0.99784069 0.03085854 0.00693498 0.04840379
 0.08575089 0.18762531 0.18385306 0.32381538 0.31857168 0.79309456
 0.80784611 0.09661985 0.28930063 0.38641609 0.2140119  0.23035757
 0.89432459 0.2586848  0.25804943 0.28042603 0.67998792 0.216241
 0.8268814  0.17459604 0.62373182 0.41003015 0.52191541 0.01766905
 0.47856021 0

KeyboardInterrupt: 

In [16]:
ac

[]

array([0.62263766, 0.9335026 , 0.29797037, ..., 0.15312717, 0.61044247,
       0.72430497])

In [102]:
a=np.asarray([1,2,3])
b = np.asarray([[4,5,6]])

In [103]:
np.matmul(b,np.transpose(a))

array([32])

In [104]:
b-a

array([[3, 3, 3]])