In [1]:
import numpy as np
import pandas as pd


In [2]:
data = open('spambase.data').read().split("\n")
data = [i.split(",") for i in (data)]
column = open('features','r').read().split("\n")
column =[i.strip() for i in column]
dataset =  pd.DataFrame(data, columns=column)
dataset=dataset.convert_objects(convert_numeric=True)
dataset=dataset.dropna()
columnmax = [max(dataset[i]) for i in dataset.columns]
columnmin = [min(dataset[i]) for i in dataset.columns]
for i,j in enumerate(dataset.columns):
    dataset[j] = (dataset[j] - columnmin[i])/columnmax[i]
dataset['class']= dataset['class'].astype(int)
# dataset.insert(0,'Bias',1)
dataset['class'].value_counts()

/Users/shaivalpatel/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:6: FutureWarning: convert_objects is deprecated.  To re-infer data dtypes for object columns, use DataFrame.infer_objects()
For all other conversions use the data-type specific converters pd.to_datetime, pd.to_timedelta and pd.to_numeric.
  


0    2788
1    1813
Name: class, dtype: int64

In [111]:
def mean_squared(W,X,Y,m):
    return (np.sum((np.matmul(X,np.transpose(W))-Y)**2))/m

In [112]:
def training(learning_rate,initial_weights,m,dataset):
    diff = 10000000000
    Y = np.asarray(list(dataset['class']))
    X = dataset.drop(columns=['class']).values
    XT=np.transpose(X)
    w_old = initial_weights
    d_old = mean_squared(initial_weights,X,Y,m)
    while diff >0.0000000000001:
        print(w_old)
        print(np.matmul(X,(np.transpose(w_old))))
        w_new = w_old - (learning_rate /m) * (np.matmul(XT,(np.matmul(X,(np.transpose(w_old)))-Y)))
        d_new = mean_squared(w_new,X,Y,m)
        diff = d_new-d_old
        d_old=d_new
        print(d_old)
        w_old = w_new
    return w_old
    

In [113]:
dataset = dataset.sample(frac=1)

b=0
while b<=0.5:
    ac=[]
    for i in range(0,len(dataset),920):
        if i+920<len(dataset):
           
            training_dataset=pd.concat([dataset[i+920:],dataset[0:i]])
            n = 57
            m = len(training_dataset)
            W=np.random.rand(n)
            print(W)
            test_dataset=dataset[i:i+920]
            weights=training(0.1,W,m,training_dataset)
            prediction=[]
            for index,row in test_dataset.iterrows():
                prediction.append(testing(row,weights))
            acc = accuracy(prediction,test_dataset)
            ac.append(acc)
    print(np.sum(np.asarray(ac))/5)
    b+=0.01

[0.76650451 0.05308169 0.15120198 0.96889054 0.31176996 0.31975215
 0.87524852 0.10970128 0.71682684 0.1694265  0.46477161 0.49164783
 0.15294086 0.73209212 0.52593625 0.49812782 0.02613574 0.71678137
 0.92821287 0.92330822 0.03282681 0.51996791 0.54296646 0.8201896
 0.88475192 0.61512509 0.62146877 0.38942837 0.30852222 0.83349861
 0.31556569 0.77829343 0.23300391 0.96539219 0.25609045 0.78064055
 0.79834812 0.40435242 0.57977477 0.31567285 0.52766846 0.26250265
 0.2824809  0.98369003 0.16777829 0.33024073 0.81468266 0.8915489
 0.76430544 0.00878251 0.81353835 0.84133277 0.76712966 0.40858795
 0.65870564 0.35119718 0.33391396]
[0.76650451 0.05308169 0.15120198 0.96889054 0.31176996 0.31975215
 0.87524852 0.10970128 0.71682684 0.1694265  0.46477161 0.49164783
 0.15294086 0.73209212 0.52593625 0.49812782 0.02613574 0.71678137
 0.92821287 0.92330822 0.03282681 0.51996791 0.54296646 0.8201896
 0.88475192 0.61512509 0.62146877 0.38942837 0.30852222 0.83349861
 0.31556569 0.77829343 0.23300

NameError: name 'testing' is not defined

array([0.62263766, 0.9335026 , 0.29797037, ..., 0.15312717, 0.61044247,
       0.72430497])

In [102]:
a=np.asarray([1,2,3])
b = np.asarray([[4,5,6]])

In [103]:
np.matmul(b,np.transpose(a))

array([32])

In [104]:
b-a

array([[3, 3, 3]])